data:
  datapath: data/
  vectordb_dirpath: vector_db/
  vector_db_name: vectordb_employee_qa
  embedding_model: "BAAI/bge-small-en-v1.5"
  

model:
  llm_model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
  temperature: 0.1
  top_k: 1
  top_p: 0.99
  repetition_penalty: 1.1
  do_sample: False
