data:
  datapath: data/
  vectordb_dirpath: vector_db/
  vector_db_name: vectordb_employee_qa
  embedding_model: "BAAI/bge-small-en-v1.5"
  

model:
  llm_model: openchat/openchat-3.5-0106 #microsoft/phi-2
  temperature: 0.1
  top_k: 1
  top_p: 0.99
  repetition_penalty: 1.1
  do_sample: False
  return_full_text: False
